function [statistics, significantPairs] = ExSeqSpatialDistributionXY( ...
        outputFolder, inputFolder, referenceImagePath, callsCsvPath, ...
        bootstrapReplicatesOverride, generateSignificantPlotsOverride)
% ExSeqSpatialDistributionXY
% Screens ExSeq expression and Moran gene-region calls for
% genotype-associated shifts along registered reference-map X and Y axes.
%
% Registration is performed once per animal, before target genes or regions
% are selected:
%   1. All molecules in annotated hippocampal regions are pooled.
%   2. Complementary tissue portions are reassembled.
%   3. A whole-map PCA shape alignment maps the animal to the reference.
%   4. A nonreflective whole-map similarity correction and a smooth global
%      landmark warp are fitted from all shared regional centroids. No
%      region receives an independent coordinate system.
%   5. The registered reference image defines the common X/Y coordinates.
%
% Each animal contributes one equally weighted spatial ECDF. The primary P
% value uses a target-excluded, animal- and region-specific transcript
% background aggregated into 10-um voxels. Every realization preserves the
% exact target molecule count, number of occupied voxels, and observed
% per-voxel cluster-size distribution.

scriptDir = fileparts(mfilename('fullpath'));
if nargin < 1 || strlength(string(outputFolder)) == 0
    outputFolder = fullfile(scriptDir, 'results', 'exseq_spatial_distribution');
end
if nargin < 2 || strlength(string(inputFolder)) == 0
    inputFolder = fullfile(scriptDir, 'data', 'exseq');
end
if nargin < 3 || strlength(string(referenceImagePath)) == 0
    referenceImagePath = fullfile(scriptDir, ...
        'hippocampus_reference_map.png');
end
if nargin < 4 || strlength(string(callsCsvPath)) == 0
    callsCsvPath = fullfile(scriptDir, 'exseq_spatial_calls.csv');
end
if ~isfolder(outputFolder)
    mkdir(outputFolder);
end

targets = readtable(callsCsvPath, 'TextType', 'string');
targets.analysis = lower(strtrim(targets.analysis));
targets.gene = upper(regexprep(strtrim(targets.gene), '\s+', ''));
targets.region = standardizeRegion(targets.region);
nExpressionCalls = sum(targets.analysis == "expression");
nMoranCalls = sum(targets.analysis == "moran");
if nExpressionCalls < 1 && nMoranCalls < 1
    error(['calls CSV must contain at least one row with analysis ' ...
        '"expression" or "moran".']);
end
fprintf('Loaded %d expression calls and %d Moran calls from %s\n', ...
    nExpressionCalls, nMoranCalls, callsCsvPath);
numberGridPoints = 301;
voxelSizeMicrons = 10;
minimumMoleculesPerAnimalRegion = 5;
minimumOccupiedVoxelsPerAnimalRegion = 3;
if nargin < 5 || isempty(bootstrapReplicatesOverride)
    numberBootstrapReplicates = 20000;
else
    numberBootstrapReplicates = bootstrapReplicatesOverride;
end
validateattributes(numberBootstrapReplicates, {'numeric'}, ...
    {'scalar', 'integer', '>=', 100});
if nargin < 6 || isempty(generateSignificantPlotsOverride)
    generateSignificantPlots = false;
else
    generateSignificantPlots = logical(generateSignificantPlotsOverride);
end
bootstrapSeed = 91841;

reference = buildReferenceTemplate(referenceImagePath);
saveReferenceTemplateAudit(reference, outputFolder);

samples = defineExseqSamples();
numberSamples = numel(samples);
numberTargets = height(targets);
emptyTarget = struct( ...
    'geneX', [], 'geneY', [], ...
    'regionAvailable', false, 'moleculeCount', 0);
axisData = repmat(emptyTarget, numberSamples, numberTargets);
emptyAudit = struct('x', [], 'y', [], 'regions', strings(0, 1), ...
    'sectionIndices', [], 'sectionFiles', strings(0, 1), ...
    'initialX', [], 'initialY', [], ...
    'initialRegions', strings(0, 1), ...
    'initialSectionIndices', [], ...
    'registeredCentroids', [], 'referenceCentroids', [], ...
    'sharedRegionNames', strings(0, 1), ...
    'analysisIncluded', true, 'excludedSectionIndices', []);
auditMaps = repmat(emptyAudit, numberSamples, 1);
emptyVoxelMap = struct( ...
    'genes', strings(0, 1), 'regions', strings(0, 1), ...
    'sectionIndices', zeros(0, 1), ...
    'voxelX', zeros(0, 1), 'voxelY', zeros(0, 1), ...
    'moleculeCounts', zeros(0, 1), ...
    'sumReferenceX', zeros(0, 1), ...
    'sumReferenceY', zeros(0, 1), ...
    'analysisIncluded', false);
voxelMaps = repmat(emptyVoxelMap, numberSamples, 1);
qcRows = table();
sectionQcRows = table();

fprintf('Registering %d complete ExSeq animal maps...\n', numberSamples);
for sampleIndex = 1:numberSamples
    fprintf('  %s (%s)\n', samples(sampleIndex).name, ...
        samples(sampleIndex).group);
    [axisData(sampleIndex, :), voxelMaps(sampleIndex), ...
        auditMaps(sampleIndex), qcRow, sampleSectionQc] = ...
        processOneAnimal(samples(sampleIndex), inputFolder, targets, ...
        reference, voxelSizeMicrons);
    qcRows = [qcRows; qcRow]; %#ok<AGROW>
    sectionQcRows = [sectionQcRows; sampleSectionQc]; %#ok<AGROW>
end

registrationFigure = plotRegistrationAudit( ...
    auditMaps, samples, reference, qcRows);
savefig(registrationFigure, fullfile(outputFolder, ...
    'ExSeq_whole_animal_reference_registration_audit.fig'));
exportgraphics(registrationFigure, fullfile(outputFolder, ...
    'ExSeq_whole_animal_reference_registration_audit.tif'), ...
    'Resolution', 300);
close(registrationFigure);

writetable(qcRows, fullfile(outputFolder, ...
    'ExSeq_reference_registration_QC.csv'));
writetable(sectionQcRows, fullfile(outputFolder, ...
    'ExSeq_reference_registration_section_QC.csv'));

sectionFigure = plotSectionRegistrationAudit( ...
    auditMaps, samples, reference, sectionQcRows);
savefig(sectionFigure, fullfile(outputFolder, ...
    'ExSeq_individual_section_registration_audit.fig'));
exportgraphics(sectionFigure, fullfile(outputFolder, ...
    'ExSeq_individual_section_registration_audit.tif'), ...
    'Resolution', 300);
close(sectionFigure);

retainedFigure = plotSectionRegistrationSubset( ...
    auditMaps, samples, reference, qcRows, sectionQcRows, ...
    sectionQcRows.analysis_included, true, ...
    'Retained tissue-part registrations used in the analysis');
savefig(retainedFigure, fullfile(outputFolder, ...
    'ExSeq_retained_section_registrations.fig'));
exportgraphics(retainedFigure, fullfile(outputFolder, ...
    'ExSeq_retained_section_registrations.tif'), ...
    'Resolution', 300);
close(retainedFigure);

discardedFigure = plotSectionRegistrationSubset( ...
    auditMaps, samples, reference, qcRows, sectionQcRows, ...
    ~sectionQcRows.analysis_included, false, ...
    'Discarded tissue-part registrations');
savefig(discardedFigure, fullfile(outputFolder, ...
    'ExSeq_discarded_section_registrations.fig'));
exportgraphics(discardedFigure, fullfile(outputFolder, ...
    'ExSeq_discarded_section_registrations.tif'), ...
    'Resolution', 300);
close(discardedFigure);

groups = string({samples.group})';
sampleNames = string({samples.name})';
sampleIncluded = qcRows.analysis_included;
statistics = table();
countRows = table();
voxelDiagnosticRows = table();
voxelTests = cell(numberTargets, 1);
testCache = containers.Map('KeyType', 'char', 'ValueType', 'any');
for targetIndex = 1:numberTargets
    analysisName = targets.analysis(targetIndex);
    geneName = targets.gene(targetIndex);
    regionName = targets.region(targetIndex);
    targetData = axisData(:, targetIndex);
    moleculeCounts = reshape([targetData.moleculeCount], [], 1);
    regionAvailable = reshape([targetData.regionAvailable], [], 1);
    countRows = [countRows; table( ... %#ok<AGROW>
        repmat(analysisName, numberSamples, 1), ...
        repmat(geneName, numberSamples, 1), ...
        repmat(regionName, numberSamples, 1), ...
        sampleNames, groups, sampleIncluded, ...
        regionAvailable, moleculeCounts, ...
        'VariableNames', {'analysis', 'gene', 'region', ...
        'sample', 'group', ...
        'analysis_included', 'region_available', ...
        'gene_molecule_count'})];

    cacheKey = char(geneName + "|" + regionName);
    if isKey(testCache, cacheKey)
        test = testCache(cacheKey);
    else
        model = prepareVoxelBackgroundModel( ...
            voxelMaps, geneName, regionName, groups, ...
            numberGridPoints, minimumMoleculesPerAnimalRegion, ...
            minimumOccupiedVoxelsPerAnimalRegion);
        rng(bootstrapSeed + targetIndex, 'twister');
        test = runVoxelBackgroundBootstrap( ...
            model, numberBootstrapReplicates);
        testCache(cacheKey) = test;
    end
    voxelTests{targetIndex} = test;

    exactX = animalLevelKsTest( ...
        targetData, 'geneX', groups, test.xGrid);
    exactY = animalLevelKsTest( ...
        targetData, 'geneY', groups, test.yGrid);
    [xRow, yRow] = makeVoxelStatisticsRows( ...
        geneName, regionName, test, exactX, exactY, ...
        voxelSizeMicrons, minimumMoleculesPerAnimalRegion, ...
        minimumOccupiedVoxelsPerAnimalRegion);
    xRow = addvars(xRow, analysisName, targetIndex, ...
        'Before', 'gene', ...
        'NewVariableNames', {'analysis', 'target_index'});
    yRow = addvars(yRow, analysisName, targetIndex, ...
        'Before', 'gene', ...
        'NewVariableNames', {'analysis', 'target_index'});
    statistics = [statistics; xRow; yRow]; %#ok<AGROW>

    animalDiagnostics = test.animalDiagnostics;
    animalDiagnostics = addvars(animalDiagnostics, ...
        repmat(analysisName, height(animalDiagnostics), 1), ...
        repmat(geneName, height(animalDiagnostics), 1), ...
        repmat(regionName, height(animalDiagnostics), 1), ...
        sampleNames(animalDiagnostics.sample_index), ...
        'Before', 1, ...
        'NewVariableNames', {'analysis', 'gene', 'region', 'sample'});
    voxelDiagnosticRows = [voxelDiagnosticRows; ...
        animalDiagnostics]; %#ok<AGROW>
end

statistics.BH_FDR_within_analysis = nan(height(statistics), 1);
analysisFamilies = ["expression", "moran"];
for analysisName = analysisFamilies
    rows = statistics.analysis == analysisName;
    statistics.BH_FDR_within_analysis(rows) = ...
        benjaminiHochberg( ...
        statistics.voxel_background_p(rows));
end
statistics.BH_FDR_all_232_axis_tests = benjaminiHochberg( ...
    statistics.voxel_background_p);
statistics.significant_BH_0p05 = ...
    statistics.BH_FDR_within_analysis <= 0.05;

xRows = 1:2:height(statistics);
yRows = 2:2:height(statistics);
significantPairs = table( ...
    (1:numberTargets)', targets.analysis, targets.gene, targets.region, ...
    statistics.voxel_level_KS_D(xRows), ...
    statistics.voxel_background_p(xRows), ...
    statistics.animal_label_permutation_p(xRows), ...
    statistics.BH_FDR_within_analysis(xRows), ...
    statistics.voxel_level_KS_D(yRows), ...
    statistics.voxel_background_p(yRows), ...
    statistics.animal_label_permutation_p(yRows), ...
    statistics.BH_FDR_within_analysis(yRows), ...
    statistics.significant_BH_0p05(xRows), ...
    statistics.significant_BH_0p05(yRows), ...
    'VariableNames', {'target_index', 'analysis', 'gene', 'region', ...
    'voxel_KS_D_X', 'voxel_background_p_X', ...
    'exact_permutation_p_X', 'BH_FDR_X', ...
    'voxel_KS_D_Y', 'voxel_background_p_Y', ...
    'exact_permutation_p_Y', 'BH_FDR_Y', ...
    'significant_X', 'significant_Y'});
significantPairs.significant_either_axis = ...
    significantPairs.significant_X | significantPairs.significant_Y;
significantAxis = repmat("none", numberTargets, 1);
significantAxis(significantPairs.significant_X) = "X";
significantAxis(significantPairs.significant_Y) = "Y";
significantAxis(significantPairs.significant_X & ...
    significantPairs.significant_Y) = "X;Y";
significantPairs.significant_axis = significantAxis;

writetable(statistics, fullfile(outputFolder, ...
    'ExSeq_spatial_axis_all_axis_tests_with_BH.csv'));
writetable(significantPairs, fullfile(outputFolder, ...
    'ExSeq_spatial_axis_gene_region_summary.csv'));
writetable(countRows, fullfile(outputFolder, ...
    'ExSeq_reference_registered_per_animal_molecule_counts.csv'));
writetable(voxelDiagnosticRows, fullfile(outputFolder, ...
    'ExSeq_voxel_background_per_animal_diagnostics.csv'));
methodParameters = table( ...
    voxelSizeMicrons, minimumMoleculesPerAnimalRegion, ...
    minimumOccupiedVoxelsPerAnimalRegion, ...
    numberBootstrapReplicates, bootstrapSeed, ...
    "target-excluded all-gene background", ...
    "weighted without replacement", ...
    'VariableNames', {'voxel_size_um', ...
    'minimum_target_molecules_per_animal_region', ...
    'minimum_occupied_target_voxels_per_animal_region', ...
    'bootstrap_replicates', 'bootstrap_seed', ...
    'background_definition', 'voxel_sampling'});
writetable(methodParameters, fullfile(outputFolder, ...
    'ExSeq_voxel_background_method_parameters.csv'));

significantTargetIndices = find( ...
    significantPairs.significant_either_axis);
if generateSignificantPlots
for targetIndex = reshape(significantTargetIndices, 1, [])
    targetData = axisData(:, targetIndex);
    test = voxelTests{targetIndex};
    xGrid = test.xGrid;
    yGrid = test.yGrid;
    [xCurves, xValid, xBandwidth] = calculateAnimalKdes( ...
        targetData, 'geneX', xGrid);
    [yCurves, yValid, yBandwidth] = calculateAnimalKdes( ...
        targetData, 'geneY', yGrid);
    xTest = makeVoxelPlotTest(test, "X");
    yTest = makeVoxelPlotTest(test, "Y");
    fig = plotTargetFigure( ...
        targets.analysis(targetIndex), ...
        targets.gene(targetIndex), targets.region(targetIndex), samples, ...
        xGrid, xCurves, xValid, xBandwidth, xTest, ...
        significantPairs.BH_FDR_X(targetIndex), ...
        yGrid, yCurves, yValid, yBandwidth, yTest, ...
        significantPairs.BH_FDR_Y(targetIndex));
    stem = sprintf('%s_%s_%s_voxel_background_BH_significant_KDE', ...
        sanitizeName(targets.analysis(targetIndex)), ...
        sanitizeName(targets.gene(targetIndex)), ...
        sanitizeName(targets.region(targetIndex)));
    savefig(fig, fullfile(outputFolder, stem + ".fig"));
    exportgraphics(fig, fullfile(outputFolder, stem + ".tif"), ...
        'Resolution', 300);
    close(fig);
end
end

fprintf(['\nTested %d gene-region calls (%d axis tests); ' ...
    '%d pairs passed BH FDR <= 0.05 in either axis.\nSaved to:\n%s\n'], ...
    numberTargets, height(statistics), numel(significantTargetIndices), ...
    outputFolder);
disp(qcRows);
disp(significantPairs(significantPairs.significant_either_axis, :));
end


function reference = buildReferenceTemplate(referenceImagePath)
if ~isfile(referenceImagePath)
    error('Reference image not found: %s', referenceImagePath);
end
imageRgb = imread(referenceImagePath);
[height, width, ~] = size(imageRgb);
imageLab = rgb2lab(im2double(imageRgb));
pixels = reshape(imageLab, [], 3);
rng(17, 'twister');
[clusterIndex, centersLab] = kmeans(pixels, 18, ...
    'MaxIter', 600, 'Replicates', 5);
centersRgb = reshape(lab2rgb(reshape(centersLab, [], 1, 3)), [], 3);
centersRgb = centersRgb .* 255;

regionNames = ["SO"; "CA1"; "DG-CA1"; "SLM"; "DG"; "Hilus"; "CA3"];
prototypeRgb = [ ...
    172, 207, 136; ...
    185,  48, 206; ...
     93, 186, 230; ...
    240, 199,  97; ...
    165,  88,  74; ...
    185,  71,  71; ...
    229, 224,  93];

numberRegions = numel(regionNames);
masks = false(height, width, numberRegions);
usedClusters = false(size(centersRgb, 1), 1);
clusterForRegion = zeros(numberRegions, 1);
for regionIndex = 1:numberRegions
    distances = vecnorm(centersRgb - prototypeRgb(regionIndex, :), 2, 2);
    distances(usedClusters) = inf;
    [~, selectedCluster] = min(distances);
    usedClusters(selectedCluster) = true;
    clusterForRegion(regionIndex) = selectedCluster;
    mask = reshape(clusterIndex == selectedCluster, height, width);
    mask = imclose(mask, strel('disk', 2, 0));
    mask = bwareaopen(mask, 25);
    mask = imfill(mask, 'holes');
    if any(mask, 'all')
        mask = bwpropfilt(mask, 'Area', 1);
    end
    masks(:, :, regionIndex) = mask;
end

centroids = nan(numberRegions, 2);
for regionIndex = 1:numberRegions
    [rows, columns] = find(masks(:, :, regionIndex));
    centroids(regionIndex, :) = [ ...
        mean(columns), height + 1 - mean(rows)];
end
unionMask = any(masks, 3);
[unionRows, unionColumns] = find(unionMask);
unionPoints = [unionColumns, height + 1 - unionRows];

reference = struct( ...
    'imageRgb', imageRgb, ...
    'height', height, ...
    'width', width, ...
    'regionNames', regionNames, ...
    'prototypeRgb', prototypeRgb, ...
    'clusterForRegion', clusterForRegion, ...
    'masks', masks, ...
    'centroids', centroids, ...
    'unionMask', unionMask, ...
    'unionPoints', unionPoints);
end


function saveReferenceTemplateAudit(reference, outputFolder)
fig = figure('Color', 'w', 'Position', [80, 80, 1050, 440]);
layout = tiledlayout(fig, 1, 2, ...
    'TileSpacing', 'compact', 'Padding', 'compact');

ax1 = nexttile(layout);
image(ax1, [1, reference.width], [1, reference.height], ...
    flipud(reference.imageRgb));
set(ax1, 'YDir', 'normal');
axis(ax1, 'image');
title(ax1, 'Supplied reference map');
xlabel(ax1, 'Reference X (pixels)');
ylabel(ax1, 'Reference Y (pixels)');

ax2 = nexttile(layout);
labelImage = ones(reference.height, reference.width, 3);
for regionIndex = 1:numel(reference.regionNames)
    mask = reference.masks(:, :, regionIndex);
    color = reference.prototypeRgb(regionIndex, :) ./ 255;
    for channel = 1:3
        layer = labelImage(:, :, channel);
        layer(mask) = color(channel);
        labelImage(:, :, channel) = layer;
    end
end
image(ax2, [1, reference.width], [1, reference.height], ...
    flipud(labelImage));
set(ax2, 'YDir', 'normal');
axis(ax2, 'image');
hold(ax2, 'on');
for regionIndex = 1:numel(reference.regionNames)
    centroid = reference.centroids(regionIndex, :);
    plot(ax2, centroid(1), centroid(2), 'ko', ...
        'MarkerFaceColor', 'w', 'MarkerSize', 5);
    text(ax2, centroid(1) + 3, centroid(2), ...
        reference.regionNames(regionIndex), ...
        'FontSize', 8, 'FontWeight', 'bold');
end
title(ax2, 'Color-derived reference labels and centroids');
xlabel(ax2, 'Reference X (pixels)');
ylabel(ax2, 'Reference Y (pixels)');
title(layout, 'Reference-template extraction used for registration', ...
    'FontSize', 14, 'FontWeight', 'bold');

savefig(fig, fullfile(outputFolder, ...
    'hippocampus_reference_template_extraction.fig'));
exportgraphics(fig, fullfile(outputFolder, ...
    'hippocampus_reference_template_extraction.tif'), ...
    'Resolution', 300);
close(fig);
end


function [targetData, voxelMap, auditMap, qcRow, sectionQcRows] = ...
        processOneAnimal(sample, inputFolder, targets, reference, ...
        voxelSizeMicrons)
rawMap = loadAndReassembleWholeAnimal(sample, inputFolder, reference);
[initialRegisteredCoordinates, initialRegistration] = registerWholeMap( ...
    rawMap.coordinates, rawMap.regions, reference);
sectionQcRows = makeSectionQcRows( ...
    sample, rawMap, initialRegisteredCoordinates, reference);

if rawMap.numberSectionsPresent > 1
    % Disconnected tissue pieces require separate rigid/global placements
    % after their requested orientation corrections. They are combined
    % only after each complete piece is mapped to the same reference.
    badSectionRows = ...
        sectionQcRows.number_shared_regions < 2 | ...
        sectionQcRows. ...
        independent_fraction_within_5px_of_matching_region < 0.50;
    grossSingleSectionFailure = false;
else
    badSectionRows = false(height(sectionQcRows), 1);
    grossSingleSectionFailure = ...
        initialRegistration.centroidRmsePixels > 50 && ...
        initialRegistration.affineDeterminant < 0.05;
end
manualDiscardRows = ...
    (string(sample.name) == "FAD1" & ...
    sectionQcRows.section_index == 1) | ...
    (string(sample.name) == "FAD6" & ...
    sectionQcRows.section_index == 1) | ...
    (string(sample.name) == "FAD5" & ...
    sectionQcRows.section_index == 1) | ...
    string(sample.name) == "WT6";
badSectionRows = badSectionRows | manualDiscardRows;
excludedSectionIndices = sectionQcRows.section_index(badSectionRows);
keptSectionMask = ~ismember(rawMap.sectionIndices, ...
    excludedSectionIndices);
analysisIncluded = any(keptSectionMask) && ...
    ~grossSingleSectionFailure;

exclusionReason = "";
if grossSingleSectionFailure
    exclusionReason = ...
        "gross whole-map fit failure (collapsed scale and centroid error)";
elseif ~any(keptSectionMask)
    if any(manualDiscardRows)
        exclusionReason = ...
            "all available tissue parts were manually excluded";
    else
        exclusionReason = ...
            "no independently registerable tissue part remains";
    end
end

sectionQcRows.part_excluded_for_misregistration = badSectionRows;
sectionQcRows.animal_excluded = ...
    repmat(~analysisIncluded, height(sectionQcRows), 1);
sectionQcRows.analysis_included = ...
    ~badSectionRows & analysisIncluded;
sectionQcRows.exclusion_reason = repmat("", height(sectionQcRows), 1);
sectionQcRows.exclusion_reason(badSectionRows) = ...
    "fewer than two regions or independent matching below 50%";
sectionQcRows.exclusion_reason(manualDiscardRows) = ...
    "manually discarded before analysis";
if ~analysisIncluded
    sectionQcRows.exclusion_reason(~badSectionRows) = exclusionReason;
end

if analysisIncluded
    analysisMap = subsetRawMap(rawMap, keptSectionMask);
    if rawMap.numberSectionsPresent > 1
        [registeredCoordinates, registration] = ...
            registerTissuePartsToCommonReference(analysisMap, reference);
    else
        registeredCoordinates = initialRegisteredCoordinates;
        registration = initialRegistration;
    end
else
    % Retain the failed initial placement only for the diagnostic audit.
    analysisMap = rawMap;
    registeredCoordinates = initialRegisteredCoordinates;
    registration = initialRegistration;
end

xReference = (registeredCoordinates(:, 1) - 1) ./ ...
    (reference.width - 1);
yReference = (registeredCoordinates(:, 2) - 1) ./ ...
    (reference.height - 1);

numberTargets = height(targets);
emptyTarget = struct( ...
    'geneX', [], 'geneY', [], ...
    'regionAvailable', false, 'moleculeCount', 0);
targetData = repmat(emptyTarget, 1, numberTargets);
if analysisIncluded
    for targetIndex = 1:numberTargets
        regionMask = analysisMap.regions == targets.region(targetIndex);
        geneMask = regionMask & ...
            analysisMap.genes == targets.gene(targetIndex);
        targetData(targetIndex) = struct( ...
            'geneX', xReference(geneMask), ...
            'geneY', yReference(geneMask), ...
            'regionAvailable', any(regionMask), ...
            'moleculeCount', sum(geneMask));
    end
end

voxelMap = aggregateGeneVoxels( ...
    analysisMap, xReference, yReference, analysisIncluded, ...
    voxelSizeMicrons);

auditKeep = evenlySpacedIndices(numel(xReference), 32000);
initialAuditKeep = evenlySpacedIndices( ...
    size(initialRegisteredCoordinates, 1), 32000);
auditMap = struct( ...
    'x', registeredCoordinates(auditKeep, 1), ...
    'y', registeredCoordinates(auditKeep, 2), ...
    'regions', analysisMap.regions(auditKeep), ...
    'sectionIndices', analysisMap.sectionIndices(auditKeep), ...
    'sectionFiles', analysisMap.sectionFiles(auditKeep), ...
    'initialX', initialRegisteredCoordinates(initialAuditKeep, 1), ...
    'initialY', initialRegisteredCoordinates(initialAuditKeep, 2), ...
    'initialRegions', rawMap.regions(initialAuditKeep), ...
    'initialSectionIndices', rawMap.sectionIndices(initialAuditKeep), ...
    'analysisIncluded', analysisIncluded, ...
    'excludedSectionIndices', excludedSectionIndices, ...
    'registeredCentroids', registration.registeredCentroids, ...
    'referenceCentroids', registration.referenceCentroids, ...
    'sharedRegionNames', registration.sharedRegionNames);

qcKeep = evenlySpacedIndices(numel(xReference), 120000);
[insideFraction, matchingFraction, medianMatchingDistance] = ...
    registrationCoverage( ...
    registeredCoordinates(qcKeep, :), ...
    analysisMap.regions(qcKeep), reference);
qcRow = table( ...
    string(sample.name), string(sample.group), ...
    rawMap.numberSectionsPresent, analysisMap.numberSectionsPresent, ...
    analysisIncluded, strjoin(string(excludedSectionIndices), ";"), ...
    exclusionReason, ...
    registration.numberSharedRegions, ...
    registration.centroidRmsePixels, ...
    registration.initialShapeScorePixels, ...
    insideFraction, matchingFraction, medianMatchingDistance, ...
    registration.initialSignX, registration.initialSignY, ...
    registration.affineDeterminant, ...
    'VariableNames', {'sample', 'group', 'number_sections_input', ...
    'number_sections_used', 'analysis_included', ...
    'excluded_section_indices', 'exclusion_reason', ...
    'number_shared_regions', 'regional_centroid_RMSE_pixels', ...
    'initial_whole_shape_score_pixels', ...
    'fraction_points_inside_reference_tissue', ...
    'fraction_points_within_5px_of_matching_region', ...
    'median_distance_to_matching_region_pixels', ...
    'initial_PCA_sign_X', 'initial_PCA_sign_Y', ...
    'global_similarity_determinant'});
end


function voxelMap = aggregateGeneVoxels( ...
        analysisMap, xReference, yReference, analysisIncluded, ...
        voxelSizeMicrons)
if ~analysisIncluded
    voxelMap = struct( ...
        'genes', strings(0, 1), 'regions', strings(0, 1), ...
        'sectionIndices', zeros(0, 1), ...
        'voxelX', zeros(0, 1), 'voxelY', zeros(0, 1), ...
        'moleculeCounts', zeros(0, 1), ...
        'sumReferenceX', zeros(0, 1), ...
        'sumReferenceY', zeros(0, 1), ...
        'analysisIncluded', false);
    return
end

voxelX = floor(analysisMap.coordinates(:, 1) ./ voxelSizeMicrons);
voxelY = floor(analysisMap.coordinates(:, 2) ./ voxelSizeMicrons);
[groupIndex, genes, regions, sectionIndices, groupedVoxelX, ...
    groupedVoxelY] = findgroups( ...
    analysisMap.genes, analysisMap.regions, ...
    analysisMap.sectionIndices, voxelX, voxelY);
moleculeCounts = splitapply(@numel, xReference, groupIndex);
sumReferenceX = splitapply(@sum, xReference, groupIndex);
sumReferenceY = splitapply(@sum, yReference, groupIndex);
voxelMap = struct( ...
    'genes', genes, ...
    'regions', regions, ...
    'sectionIndices', sectionIndices, ...
    'voxelX', groupedVoxelX, ...
    'voxelY', groupedVoxelY, ...
    'moleculeCounts', moleculeCounts, ...
    'sumReferenceX', sumReferenceX, ...
    'sumReferenceY', sumReferenceY, ...
    'analysisIncluded', true);
end


function rawMap = loadAndReassembleWholeAnimal(sample, inputFolder, reference)
numberFiles = numel(sample.files);
emptySection = struct( ...
    'coordinates', zeros(0, 2), ...
    'genes', strings(0, 1), ...
    'regions', strings(0, 1), ...
    'fileName', "");
sections = repmat(emptySection, numberFiles, 1);
sectionWidths = zeros(numberFiles, 1);

for fileIndex = 1:numberFiles
    filePath = fullfile(inputFolder, sample.files{fileIndex});
    if ~isfile(filePath)
        error('Missing ExSeq file: %s', filePath);
    end
    options = detectImportOptions(filePath);
    names = string(options.VariableNames);
    geneColumn = findColumn(names, ["gene", "genes", "gene_name"]);
    regionColumn = findColumn(names, ...
        ["region_name", "region", "hippocampal_region"]);
    xColumn = findColumn(names, ["global_x_um", "x_um", "x"]);
    yColumn = findColumn(names, ["global_y_um", "y_um", "y"]);
    selected = [geneColumn, regionColumn, xColumn, yColumn];
    if any(strlength(selected) == 0)
        error('Required columns were not found in %s.', filePath);
    end
    options.SelectedVariableNames = cellstr(selected);
    T = readtable(filePath, options);

    genes = upper(regexprep(strtrim(string(T.(char(geneColumn)))), ...
        '\s+', ''));
    regions = standardizeRegion(T.(char(regionColumn)));
    x = double(T.(char(xColumn)));
    y = double(T.(char(yColumn)));
    keep = isfinite(x) & isfinite(y) & ...
        ismember(regions, reference.regionNames);
    coordinates = [x(keep), y(keep)];
    genes = genes(keep);
    regions = regions(keep);

    [rotationDegrees, mirrorLeftRight] = sectionOrientation( ...
        sample.name, fileIndex);
    coordinates = transformSectionCoordinates( ...
        coordinates, rotationDegrees, mirrorLeftRight);
    sectionWidths(fileIndex) = range(coordinates(:, 1));
    sections(fileIndex) = struct( ...
        'coordinates', coordinates, ...
        'genes', genes, ...
        'regions', regions, ...
        'fileName', string(sample.files{fileIndex}));
    clear T genes regions x y
end

positiveWidths = sectionWidths(sectionWidths > 0);
if isempty(positiveWidths)
    error('No annotated hippocampal molecules found for %s.', sample.name);
end
typicalWidth = median(positiveWidths);
gap = 0.025 .* typicalWidth;
offset = 0;
referenceMedianY = [];
coordinates = zeros(0, 2);
genes = strings(0, 1);
regions = strings(0, 1);
sectionIndices = zeros(0, 1);
sectionFiles = strings(0, 1);
for fileIndex = 1:numberFiles
    section = sections(fileIndex);
    if isempty(section.coordinates)
        continue
    end
    if isempty(referenceMedianY)
        referenceMedianY = median(section.coordinates(:, 2), 'omitnan');
    end
    yOffset = referenceMedianY - ...
        median(section.coordinates(:, 2), 'omitnan');
    yOffset = yOffset + sectionVerticalAdjustment( ...
        sample.name, fileIndex, typicalWidth);
    section.coordinates(:, 1) = section.coordinates(:, 1) + offset;
    section.coordinates(:, 2) = section.coordinates(:, 2) + yOffset;
    coordinates = [coordinates; section.coordinates]; %#ok<AGROW>
    genes = [genes; section.genes]; %#ok<AGROW>
    regions = [regions; section.regions]; %#ok<AGROW>
    sectionIndices = [sectionIndices; ...
        repmat(fileIndex, size(section.coordinates, 1), 1)]; %#ok<AGROW>
    sectionFiles = [sectionFiles; ...
        repmat(section.fileName, size(section.coordinates, 1), 1)]; %#ok<AGROW>
    offset = offset + sectionWidths(fileIndex) + gap;
end

rawMap = struct( ...
    'coordinates', coordinates, ...
    'genes', genes, ...
    'regions', regions, ...
    'sectionIndices', sectionIndices, ...
    'sectionFiles', sectionFiles, ...
    'numberSectionsPresent', sum(sectionWidths > 0));
end


function subset = subsetRawMap(rawMap, keep)
subset = struct( ...
    'coordinates', rawMap.coordinates(keep, :), ...
    'genes', rawMap.genes(keep), ...
    'regions', rawMap.regions(keep), ...
    'sectionIndices', rawMap.sectionIndices(keep), ...
    'sectionFiles', rawMap.sectionFiles(keep), ...
    'numberSectionsPresent', numel(unique(rawMap.sectionIndices(keep))));
end


function [registered, result] = registerTissuePartsToCommonReference( ...
        rawMap, reference)
registered = nan(size(rawMap.coordinates));
sectionNumbers = unique(rawMap.sectionIndices, 'stable');
for sectionNumber = reshape(sectionNumbers, 1, [])
    sectionMask = rawMap.sectionIndices == sectionNumber;
    registered(sectionMask, :) = registerWholeMap( ...
        rawMap.coordinates(sectionMask, :), ...
        rawMap.regions(sectionMask), reference);
end

[registeredCentroids, referenceCentroids, sharedRegionNames] = ...
    sharedRegionCentroids(registered, rawMap.regions, reference);
residual = registeredCentroids - referenceCentroids;
centroidRmse = sqrt(mean(sum(residual .^ 2, 2)));
result = struct( ...
    'numberSharedRegions', numel(sharedRegionNames), ...
    'centroidRmsePixels', centroidRmse, ...
    'initialShapeScorePixels', NaN, ...
    'initialSignX', NaN, ...
    'initialSignY', NaN, ...
    'affineDeterminant', NaN, ...
    'registeredCentroids', registeredCentroids, ...
    'referenceCentroids', referenceCentroids, ...
    'sharedRegionNames', sharedRegionNames);
end


function rows = makeSectionQcRows( ...
        sample, rawMap, registeredCoordinates, reference)
sectionNumbers = unique(rawMap.sectionIndices, 'stable');
rows = table();
for sectionNumber = reshape(sectionNumbers, 1, [])
    sectionMask = rawMap.sectionIndices == sectionNumber;
    sectionCoordinates = registeredCoordinates(sectionMask, :);
    sectionRegions = rawMap.regions(sectionMask);
    keep = evenlySpacedIndices(size(sectionCoordinates, 1), 120000);
    [insideFraction, matchingFraction, medianMatchingDistance] = ...
        registrationCoverage( ...
        sectionCoordinates(keep, :), sectionRegions(keep), reference);
    [movingCentroids, fixedCentroids, sharedRegionNames] = ...
        sharedRegionCentroids(sectionCoordinates, sectionRegions, reference);
    centroidResiduals = movingCentroids - fixedCentroids;
    centroidRmse = sqrt(mean(sum(centroidResiduals .^ 2, 2)));
    independentlyRegistered = registerWholeMap( ...
        rawMap.coordinates(sectionMask, :), sectionRegions, reference);
    independentKeep = evenlySpacedIndices( ...
        size(independentlyRegistered, 1), 120000);
    [independentInsideFraction, independentMatchingFraction, ...
        independentMedianDistance] = registrationCoverage( ...
        independentlyRegistered(independentKeep, :), ...
        sectionRegions(independentKeep), reference);
    recoverableMatchingGain = ...
        independentMatchingFraction - matchingFraction;
    fileName = rawMap.sectionFiles(find(sectionMask, 1));
    rows = [rows; table( ... %#ok<AGROW>
        string(sample.name), string(sample.group), sectionNumber, ...
        fileName, sum(sectionMask), numel(sharedRegionNames), ...
        strjoin(sharedRegionNames, ";"), centroidRmse, ...
        insideFraction, matchingFraction, medianMatchingDistance, ...
        independentInsideFraction, independentMatchingFraction, ...
        independentMedianDistance, recoverableMatchingGain, ...
        'VariableNames', {'sample', 'group', 'section_index', ...
        'section_file', 'annotated_molecule_count', ...
        'number_shared_regions', 'shared_regions', ...
        'regional_centroid_RMSE_pixels', ...
        'fraction_points_inside_reference_tissue', ...
        'fraction_points_within_5px_of_matching_region', ...
        'median_distance_to_matching_region_pixels', ...
        'independent_fraction_inside_reference_tissue', ...
        'independent_fraction_within_5px_of_matching_region', ...
        'independent_median_distance_to_matching_region_pixels', ...
        'recoverable_matching_fraction_gain'})];
end
end


function coordinates = transformSectionCoordinates( ...
        coordinates, rotationDegrees, mirrorLeftRight)
center = median(coordinates, 1, 'omitnan');
coordinates = coordinates - center;
if mirrorLeftRight
    coordinates(:, 1) = -coordinates(:, 1);
end
angle = deg2rad(rotationDegrees);
rotation = [cos(angle), -sin(angle); sin(angle), cos(angle)];
coordinates = coordinates * rotation';
coordinates = coordinates - min(coordinates, [], 1);
end


function [registered, result] = registerWholeMap( ...
        coordinates, regions, reference)
shapeKeep = evenlySpacedIndices(size(coordinates, 1), 50000);
shapeCoordinates = coordinates(shapeKeep, :);
[shapeCandidates, shapeScores, signCandidates] = ...
    initializeWholeShapeCandidates( ...
    coordinates, shapeCoordinates, reference);

bestSelectionScore = inf;
registered = [];
registeredCentroids = [];
referenceCentroids = [];
similarityDeterminant = NaN;
initialShape = NaN;
signX = NaN;
signY = NaN;
for candidateIndex = 1:numel(shapeCandidates)
    initialAll = shapeCandidates{candidateIndex};
    [movingCandidate, fixedCandidate, ~] = ...
        sharedRegionCentroids(initialAll, regions, reference);
    if size(movingCandidate, 1) >= 2
        [candidateRegistered, candidateCentroids, ...
            candidateDeterminant] = applyNonreflectiveSimilarity( ...
            initialAll, movingCandidate, fixedCandidate);
    else
        candidateRegistered = initialAll;
        candidateCentroids = movingCandidate;
        candidateDeterminant = NaN;
    end

    scoreKeep = evenlySpacedIndices(size(candidateRegistered, 1), 30000);
    [~, candidateMatchingFraction, candidateMedianDistance] = ...
        registrationCoverage( ...
        candidateRegistered(scoreKeep, :), regions(scoreKeep), reference);
    selectionScore = candidateMedianDistance + ...
        20 .* (1 - candidateMatchingFraction) + ...
        0.10 .* shapeScores(candidateIndex);
    if selectionScore < bestSelectionScore
        bestSelectionScore = selectionScore;
        registered = candidateRegistered;
        registeredCentroids = candidateCentroids;
        referenceCentroids = fixedCandidate;
        similarityDeterminant = candidateDeterminant;
        initialShape = shapeScores(candidateIndex);
        signX = signCandidates(candidateIndex, 1);
        signY = signCandidates(candidateIndex, 2);
    end
end

% Refine only the selected whole-map solution. Two modest passes allow the
% smooth field to approach the landmarks without permitting affine shear.
for refinementPass = 1:2
    registered = applySmoothLandmarkWarp( ...
        registered, registeredCentroids, referenceCentroids, reference);
    [registeredCentroids, ~, sharedRegionNames] = ...
        sharedRegionCentroids(registered, regions, reference);
end
residual = registeredCentroids - referenceCentroids;
centroidRmse = sqrt(mean(sum(residual .^ 2, 2)));

result = struct( ...
    'numberSharedRegions', numel(sharedRegionNames), ...
    'centroidRmsePixels', centroidRmse, ...
    'initialShapeScorePixels', initialShape, ...
    'initialSignX', signX, ...
    'initialSignY', signY, ...
    'affineDeterminant', similarityDeterminant, ...
    'registeredCentroids', registeredCentroids, ...
    'referenceCentroids', referenceCentroids, ...
    'sharedRegionNames', sharedRegionNames);
end


function [candidates, scores, signCandidates] = ...
        initializeWholeShapeCandidates( ...
        allCoordinates, shapeCoordinates, reference)
referencePoints = reference.unionPoints;
[sourceCenter, sourceVectors, sourceSpans] = ...
    principalCoordinateSystem(shapeCoordinates);
[referenceCenter, referenceVectors, referenceSpans] = ...
    principalCoordinateSystem(referencePoints);

sourceScoresAll = (allCoordinates - sourceCenter) * sourceVectors;
sourceScoresShape = (shapeCoordinates - sourceCenter) * sourceVectors;
scale = referenceSpans ./ sourceSpans;
signCandidates = [1, 1; -1, 1; 1, -1; -1, -1];
distanceImage = bwdist(reference.unionMask);
candidates = cell(size(signCandidates, 1), 1);
scores = nan(size(signCandidates, 1), 1);
for candidateIndex = 1:size(signCandidates, 1)
    signs = signCandidates(candidateIndex, :);
    candidateScores = sourceScoresShape .* scale .* signs;
    mappedShape = candidateScores * referenceVectors' + referenceCenter;
    scores(candidateIndex) = pointToMaskDistance( ...
        mappedShape, distanceImage, reference);
    mappedScores = sourceScoresAll .* scale .* signs;
    candidates{candidateIndex} = ...
        mappedScores * referenceVectors' + referenceCenter;
end
end


function [center, vectors, spans] = principalCoordinateSystem(points)
center = median(points, 1, 'omitnan');
centered = points - center;
covariance = cov(centered, 'omitrows');
[vectors, values] = eig(covariance, 'vector');
[~, order] = sort(values, 'descend');
vectors = vectors(:, order);
scores = centered * vectors;
spans = prctile(scores, 95, 1) - prctile(scores, 5, 1);
spans(spans <= 0) = 1;
end


function score = pointToMaskDistance(points, distanceImage, reference)
columns = points(:, 1);
rows = reference.height + 1 - points(:, 2);
insideCanvas = columns >= 1 & columns <= reference.width & ...
    rows >= 1 & rows <= reference.height;
distances = repmat(0.25 .* max(reference.width, reference.height), ...
    size(columns));
distances(insideCanvas) = interp2( ...
    distanceImage, columns(insideCanvas), rows(insideCanvas), ...
    'linear', max(reference.width, reference.height));
score = mean(min(distances, 50), 'omitnan');
end


function [movingCentroids, fixedCentroids, sharedRegionNames] = ...
        sharedRegionCentroids(coordinates, regions, reference)
movingCentroids = [];
fixedCentroids = [];
sharedRegionNames = strings(0, 1);
for regionIndex = 1:numel(reference.regionNames)
    regionName = reference.regionNames(regionIndex);
    mask = regions == regionName;
    if any(mask)
        movingCentroids(end + 1, :) = ... %#ok<AGROW>
            mean(coordinates(mask, :), 1, 'omitnan');
        fixedCentroids(end + 1, :) = ... %#ok<AGROW>
            reference.centroids(regionIndex, :);
        sharedRegionNames(end + 1, 1) = regionName; %#ok<AGROW>
    end
end
end


function [registered, registeredCentroids, determinantValue] = ...
        applyNonreflectiveSimilarity(coordinates, moving, fixed)
[~, registeredCentroids, transform] = procrustes( ...
    fixed, moving, 'Scaling', true, 'Reflection', false);
translation = transform.c(1, :);
registered = transform.b .* coordinates * transform.T + translation;
determinantValue = det(transform.b .* transform.T);
end


function warped = applySmoothLandmarkWarp( ...
        coordinates, movingLandmarks, fixedLandmarks, reference)
if isempty(movingLandmarks)
    warped = coordinates;
    return
end

displacements = fixedLandmarks - movingLandmarks;
maximumDisplacement = 0.22 .* hypot(reference.width, reference.height);
displacementNorms = vecnorm(displacements, 2, 2);
displacementScale = min(1, ...
    maximumDisplacement ./ max(displacementNorms, eps));
displacements = bsxfun(@times, displacements, displacementScale(:));

boundaryAnchors = [ ...
    1, 1; reference.width, 1; ...
    1, reference.height; reference.width, reference.height; ...
    reference.width ./ 2, 1; reference.width ./ 2, reference.height; ...
    1, reference.height ./ 2; reference.width, reference.height ./ 2];
landmarks = [movingLandmarks; boundaryAnchors];
displacements = [displacements; zeros(size(boundaryAnchors))];
landmarkStrength = [ ...
    repmat(3, size(movingLandmarks, 1), 1); ...
    repmat(0.6, size(boundaryAnchors, 1), 1)];
sigma = 0.16 .* hypot(reference.width, reference.height);

warped = coordinates;
chunkSize = 100000;
for firstRow = 1:chunkSize:size(coordinates, 1)
    lastRow = min(firstRow + chunkSize - 1, size(coordinates, 1));
    chunk = coordinates(firstRow:lastRow, :);
    deltaX = chunk(:, 1) - landmarks(:, 1)';
    deltaY = chunk(:, 2) - landmarks(:, 2)';
    weights = exp(-(deltaX .^ 2 + deltaY .^ 2) ./ ...
        (2 .* sigma .^ 2)) .* landmarkStrength';
    weights = weights ./ max(sum(weights, 2), eps);
    warped(firstRow:lastRow, :) = chunk + weights * displacements;
end
end


function [insideFraction, matchingFraction, medianMatchingDistance] = ...
        registrationCoverage(coordinates, regions, reference)
columns = round(coordinates(:, 1));
rows = round(reference.height + 1 - coordinates(:, 2));
insideCanvas = columns >= 1 & columns <= reference.width & ...
    rows >= 1 & rows <= reference.height;
insideReference = false(size(columns));
validLinear = sub2ind( ...
    [reference.height, reference.width], ...
    min(max(rows, 1), reference.height), ...
    min(max(columns, 1), reference.width));
insideReference(insideCanvas) = ...
    reference.unionMask(validLinear(insideCanvas));
insideFraction = mean(insideReference);

matching = false(size(columns));
matchingDistances = nan(size(columns));
for regionIndex = 1:numel(reference.regionNames)
    regionMask = regions == reference.regionNames(regionIndex);
    if ~any(regionMask)
        continue
    end
    distanceImage = bwdist(reference.masks(:, :, regionIndex));
    regionCoordinates = coordinates(regionMask, :);
    regionColumns = regionCoordinates(:, 1);
    regionRows = reference.height + 1 - regionCoordinates(:, 2);
    inCanvas = regionColumns >= 1 & regionColumns <= reference.width & ...
        regionRows >= 1 & regionRows <= reference.height;
    distances = repmat(max(reference.width, reference.height), ...
        sum(regionMask), 1);
    distances(inCanvas) = interp2( ...
        distanceImage, regionColumns(inCanvas), regionRows(inCanvas), ...
        'linear', max(reference.width, reference.height));
    matching(regionMask) = distances <= 5;
    matchingDistances(regionMask) = distances;
end
matchingFraction = mean(matching);
medianMatchingDistance = median(matchingDistances, 'omitnan');
end


function fig = plotRegistrationAudit(auditMaps, samples, reference, qcRows)
fig = figure('Color', 'w', 'Position', [20, 20, 1550, 1120]);
layout = tiledlayout(fig, 3, 4, ...
    'TileSpacing', 'compact', 'Padding', 'loose');
for sampleIndex = 1:numel(samples)
    ax = nexttile(layout);
    image(ax, [1, reference.width], [1, reference.height], ...
        flipud(reference.imageRgb));
    set(ax, 'YDir', 'normal');
    hold(ax, 'on');
    map = auditMaps(sampleIndex);
    for regionIndex = 1:numel(reference.regionNames)
        regionName = reference.regionNames(regionIndex);
        rows = map.regions == regionName;
        if ~any(rows)
            continue
        end
        color = reference.prototypeRgb(regionIndex, :) ./ 255;
        scatter(ax, map.x(rows), map.y(rows), 3, color, 'filled', ...
            'MarkerFaceAlpha', 0.22, 'MarkerEdgeAlpha', 0.22);
    end
    for landmarkIndex = 1:size(map.registeredCentroids, 1)
        moving = map.registeredCentroids(landmarkIndex, :);
        fixed = map.referenceCentroids(landmarkIndex, :);
        plot(ax, [moving(1), fixed(1)], [moving(2), fixed(2)], ...
            '-', 'Color', [0.15, 0.15, 0.15, 0.55], 'LineWidth', 0.7);
        plot(ax, moving(1), moving(2), 'wo', ...
            'MarkerFaceColor', 'k', 'MarkerSize', 3.5);
        plot(ax, fixed(1), fixed(2), 'wx', ...
            'MarkerSize', 5, 'LineWidth', 1);
    end
    xlim(ax, [1, reference.width]);
    ylim(ax, [1, reference.height]);
    axis(ax, 'image');
    box(ax, 'on');
    ax.XTick = [];
    ax.YTick = [];
    if samples(sampleIndex).group == "WT"
        titleColor = [0.12, 0.58, 0.24];
    else
        titleColor = [0.88, 0.20, 0.18];
    end
    title(ax, sprintf([ ...
        '%s (%s): %d regions | RMSE %.1f px | matching %.1f%%'], ...
        samples(sampleIndex).name, samples(sampleIndex).group, ...
        qcRows.number_shared_regions(sampleIndex), ...
        qcRows.regional_centroid_RMSE_pixels(sampleIndex), ...
        100 .* qcRows.fraction_points_within_5px_of_matching_region( ...
        sampleIndex)), ...
        'Color', titleColor, 'FontSize', 7.2);
    if ~qcRows.analysis_included(sampleIndex)
        title(ax, sprintf('%s (%s): EXCLUDED | %s', ...
            samples(sampleIndex).name, samples(sampleIndex).group, ...
            qcRows.exclusion_reason(sampleIndex)), ...
            'Color', [0.65, 0.05, 0.05], 'FontSize', 7.2, ...
            'Interpreter', 'none');
    elseif strlength(qcRows.excluded_section_indices(sampleIndex)) > 0
        title(ax, sprintf([ ...
            '%s (%s): retained after excluding part %s | matching %.1f%%'], ...
            samples(sampleIndex).name, samples(sampleIndex).group, ...
            qcRows.excluded_section_indices(sampleIndex), ...
            100 .* qcRows.fraction_points_within_5px_of_matching_region( ...
            sampleIndex)), ...
            'Color', titleColor, 'FontSize', 7.2);
    end
end
end


function fig = plotSectionRegistrationAudit( ...
        auditMaps, samples, reference, sectionQcRows)
numberSections = height(sectionQcRows);
numberColumns = 4;
numberRows = ceil(numberSections ./ numberColumns);
fig = figure('Color', 'w', 'Position', [20, 20, 1550, 360 .* numberRows]);
layout = tiledlayout(fig, numberRows, numberColumns, ...
    'TileSpacing', 'compact', 'Padding', 'loose');
for rowIndex = 1:numberSections
    ax = nexttile(layout);
    image(ax, [1, reference.width], [1, reference.height], ...
        flipud(reference.imageRgb));
    set(ax, 'YDir', 'normal');
    hold(ax, 'on');

    sampleIndex = find( ...
        string({samples.name}) == sectionQcRows.sample(rowIndex), 1);
    map = auditMaps(sampleIndex);
    sectionRows = map.initialSectionIndices == ...
        sectionQcRows.section_index(rowIndex);
    for regionIndex = 1:numel(reference.regionNames)
        regionName = reference.regionNames(regionIndex);
        pointRows = sectionRows & map.initialRegions == regionName;
        if ~any(pointRows)
            continue
        end
        color = reference.prototypeRgb(regionIndex, :) ./ 255;
        scatter(ax, map.initialX(pointRows), map.initialY(pointRows), ...
            3, color, ...
            'filled', 'MarkerFaceAlpha', 0.28, ...
            'MarkerEdgeAlpha', 0.28);
    end

    xlim(ax, [1, reference.width]);
    ylim(ax, [1, reference.height]);
    axis(ax, 'image');
    box(ax, 'on');
    ax.XTick = [];
    ax.YTick = [];
    if ~sectionQcRows.analysis_included(rowIndex)
        titleColor = [0.65, 0.05, 0.05];
        statusText = "EXCLUDED: " + ...
            sectionQcRows.exclusion_reason(rowIndex);
    elseif sectionQcRows.group(rowIndex) == "WT"
        titleColor = [0.12, 0.58, 0.24];
        statusText = "RETAINED";
    else
        titleColor = [0.88, 0.20, 0.18];
        statusText = "RETAINED";
    end
    [~, shortFile, extension] = fileparts( ...
        sectionQcRows.section_file(rowIndex));
    title(ax, { ...
        sprintf('%s part %d: %s%s', sectionQcRows.sample(rowIndex), ...
        sectionQcRows.section_index(rowIndex), shortFile, extension), ...
        sprintf('inside %.1f%% | matching %.1f%% | median %.1f px | RMSE %.1f px', ...
        100 .* sectionQcRows.fraction_points_inside_reference_tissue(rowIndex), ...
        100 .* sectionQcRows.fraction_points_within_5px_of_matching_region(rowIndex), ...
        sectionQcRows.median_distance_to_matching_region_pixels(rowIndex), ...
        sectionQcRows.regional_centroid_RMSE_pixels(rowIndex)), ...
        statusText}, ...
        'Color', titleColor, 'FontSize', 6.6, ...
        'Interpreter', 'none');
end
end


function fig = plotSectionRegistrationSubset( ...
        auditMaps, samples, reference, qcRows, sectionQcRows, ...
        rowsToPlot, useFinalRegistration, figureName)
selectedRows = find(rowsToPlot);
numberPanels = numel(selectedRows);
if numberPanels >= 8
    numberColumns = 5;
else
    numberColumns = 3;
end
numberRows = ceil(numberPanels ./ numberColumns);
fig = figure('Color', 'w', 'Name', figureName, ...
    'Position', [20, 20, 1750, 390 .* numberRows]);
layout = tiledlayout(fig, numberRows, numberColumns, ...
    'TileSpacing', 'compact', 'Padding', 'loose');

for panelIndex = 1:numberPanels
    rowIndex = selectedRows(panelIndex);
    ax = nexttile(layout);
    image(ax, [1, reference.width], [1, reference.height], ...
        flipud(reference.imageRgb));
    set(ax, 'YDir', 'normal');
    hold(ax, 'on');

    sampleIndex = find( ...
        string({samples.name}) == sectionQcRows.sample(rowIndex), 1);
    map = auditMaps(sampleIndex);
    sectionIndex = sectionQcRows.section_index(rowIndex);
    if useFinalRegistration
        x = map.x;
        y = map.y;
        regions = map.regions;
        sectionIndices = map.sectionIndices;
    else
        x = map.initialX;
        y = map.initialY;
        regions = map.initialRegions;
        sectionIndices = map.initialSectionIndices;
    end
    sectionRows = sectionIndices == sectionIndex;
    for regionIndex = 1:numel(reference.regionNames)
        pointRows = sectionRows & ...
            regions == reference.regionNames(regionIndex);
        if ~any(pointRows)
            continue
        end
        color = reference.prototypeRgb(regionIndex, :) ./ 255;
        scatter(ax, x(pointRows), y(pointRows), 3, color, ...
            'filled', 'MarkerFaceAlpha', 0.30, ...
            'MarkerEdgeAlpha', 0.30);
    end

    xlim(ax, [1, reference.width]);
    ylim(ax, [1, reference.height]);
    axis(ax, 'image');
    box(ax, 'on');
    ax.XTick = [];
    ax.YTick = [];
    [~, shortFile, extension] = fileparts( ...
        sectionQcRows.section_file(rowIndex));

    if useFinalRegistration
        titleColor = [0.08, 0.48, 0.20];
        titleLines = { ...
            sprintf('%s part %d: %s%s', ...
            sectionQcRows.sample(rowIndex), sectionIndex, ...
            shortFile, extension), ...
            sprintf('RETAINED | final matching %.1f%% | RMSE %.1f px', ...
            100 .* qcRows.fraction_points_within_5px_of_matching_region( ...
            sampleIndex), ...
            qcRows.regional_centroid_RMSE_pixels(sampleIndex))};
    else
        titleColor = [0.72, 0.05, 0.05];
        titleLines = { ...
            sprintf('%s part %d: %s%s', ...
            sectionQcRows.sample(rowIndex), sectionIndex, ...
            shortFile, extension), ...
            sprintf('DISCARDED | matching %.1f%% | RMSE %.1f px', ...
            100 .* sectionQcRows. ...
            fraction_points_within_5px_of_matching_region(rowIndex), ...
            sectionQcRows.regional_centroid_RMSE_pixels(rowIndex)), ...
            sectionQcRows.exclusion_reason(rowIndex)};
    end
    title(ax, titleLines, 'Color', titleColor, ...
        'FontSize', 7.2, 'Interpreter', 'none');
end
end


function gridValues = makeReferenceGrid(targetData, fieldName, numberPoints)
allValues = [];
for animalIndex = 1:numel(targetData)
    values = targetData(animalIndex).(fieldName);
    allValues = [allValues; values(isfinite(values))]; %#ok<AGROW>
end
if isempty(allValues)
    gridValues = linspace(-0.02, 1.02, numberPoints);
    return
end
lower = min([0; allValues]);
upper = max([1; allValues]);
padding = 0.02 .* max(upper - lower, 1);
gridValues = linspace(lower - padding, upper + padding, numberPoints);
end


function [curves, valid, commonBandwidth] = calculateAnimalKdes( ...
        targetData, fieldName, evaluationGrid)
numberAnimals = numel(targetData);
valid = false(numberAnimals, 1);
individualBandwidths = nan(numberAnimals, 1);
for animalIndex = 1:numberAnimals
    values = targetData(animalIndex).(fieldName);
    values = values(isfinite(values));
    valid(animalIndex) = ~isempty(values);
    if numel(values) >= 2 && range(values) > 0
        [~, ~, individualBandwidths(animalIndex)] = ksdensity(values);
    end
end
commonBandwidth = median(individualBandwidths, 'omitnan');
if ~isfinite(commonBandwidth) || commonBandwidth <= 0
    commonBandwidth = range(evaluationGrid) ./ 30;
end

curves = nan(numberAnimals, numel(evaluationGrid));
for animalIndex = find(valid)'
    values = targetData(animalIndex).(fieldName);
    values = values(isfinite(values));
    curve = ksdensity(values, evaluationGrid, ...
        'Bandwidth', commonBandwidth);
    curveArea = trapz(evaluationGrid, curve);
    if isfinite(curveArea) && curveArea > 0
        curve = curve ./ curveArea;
    end
    curves(animalIndex, :) = curve;
end
end


function model = prepareVoxelBackgroundModel( ...
        voxelMaps, geneName, regionName, groups, numberGridPoints, ...
        minimumMolecules, minimumOccupiedVoxels)
numberAnimals = numel(voxelMaps);
emptyAnimal = struct( ...
    'group', "", 'regionAvailable', false, ...
    'targetMoleculeCount', 0, 'targetOccupiedVoxels', 0, ...
    'backgroundEligibleVoxels', 0, 'valid', false, ...
    'invalidReason', "", ...
    'targetClusterCounts', zeros(0, 1), ...
    'targetX', zeros(0, 1), 'targetY', zeros(0, 1), ...
    'backgroundWeights', zeros(0, 1), ...
    'backgroundX', zeros(0, 1), 'backgroundY', zeros(0, 1));
animalData = repmat(emptyAnimal, numberAnimals, 1);
allX = [];
allY = [];

for animalIndex = 1:numberAnimals
    map = voxelMaps(animalIndex);
    animal = emptyAnimal;
    animal.group = groups(animalIndex);
    if ~map.analysisIncluded
        animal.invalidReason = "animal excluded by registration QC";
        animalData(animalIndex) = animal;
        continue
    end

    regionRows = map.regions == regionName;
    animal.regionAvailable = any(regionRows);
    if ~animal.regionAvailable
        animal.invalidReason = "region absent";
        animalData(animalIndex) = animal;
        continue
    end

    targetRows = regionRows & map.genes == geneName;
    targetCounts = map.moleculeCounts(targetRows);
    animal.targetMoleculeCount = sum(targetCounts);
    animal.targetOccupiedVoxels = numel(targetCounts);
    if ~isempty(targetCounts)
        animal.targetClusterCounts = targetCounts;
        animal.targetX = map.sumReferenceX(targetRows) ./ targetCounts;
        animal.targetY = map.sumReferenceY(targetRows) ./ targetCounts;
    end

    backgroundRows = regionRows & map.genes ~= geneName;
    if any(backgroundRows)
        [backgroundGroup, ~, ~, ~] = findgroups( ...
            map.sectionIndices(backgroundRows), ...
            map.voxelX(backgroundRows), map.voxelY(backgroundRows));
        backgroundCounts = splitapply( ...
            @sum, map.moleculeCounts(backgroundRows), backgroundGroup);
        backgroundSumX = splitapply( ...
            @sum, map.sumReferenceX(backgroundRows), backgroundGroup);
        backgroundSumY = splitapply( ...
            @sum, map.sumReferenceY(backgroundRows), backgroundGroup);
        animal.backgroundEligibleVoxels = numel(backgroundCounts);
        animal.backgroundWeights = backgroundCounts ./ ...
            sum(backgroundCounts);
        animal.backgroundX = backgroundSumX ./ backgroundCounts;
        animal.backgroundY = backgroundSumY ./ backgroundCounts;
    end

    if animal.targetMoleculeCount < minimumMolecules
        animal.invalidReason = "fewer than minimum target molecules";
    elseif animal.targetOccupiedVoxels < minimumOccupiedVoxels
        animal.invalidReason = "fewer than minimum occupied target voxels";
    elseif animal.backgroundEligibleVoxels < ...
            animal.targetOccupiedVoxels
        animal.invalidReason = ...
            "fewer eligible background voxels than target clusters";
    else
        animal.valid = true;
        allX = [allX; animal.targetX; animal.backgroundX]; %#ok<AGROW>
        allY = [allY; animal.targetY; animal.backgroundY]; %#ok<AGROW>
    end
    animalData(animalIndex) = animal;
end

xGrid = makeCoordinateGrid(allX, numberGridPoints);
yGrid = makeCoordinateGrid(allY, numberGridPoints);
valid = reshape([animalData.valid], [], 1);
validGroups = groups(valid);
numberWT = sum(validGroups == "WT");
numberFAD = sum(validGroups == "FAD");

animalCdfX = nan(numberAnimals, numberGridPoints);
animalCdfY = nan(numberAnimals, numberGridPoints);
for animalIndex = find(valid)'
    animal = animalData(animalIndex);
    animalCdfX(animalIndex, :) = weightedSpatialCdf( ...
        animal.targetX, animal.targetClusterCounts, xGrid);
    animalCdfY(animalIndex, :) = weightedSpatialCdf( ...
        animal.targetY, animal.targetClusterCounts, yGrid);
end

if numberWT >= 2 && numberFAD >= 2
    observedX = max(abs( ...
        mean(animalCdfX(valid & groups == "WT", :), 1) - ...
        mean(animalCdfX(valid & groups == "FAD", :), 1)));
    observedY = max(abs( ...
        mean(animalCdfY(valid & groups == "WT", :), 1) - ...
        mean(animalCdfY(valid & groups == "FAD", :), 1)));
    testable = true;
else
    observedX = NaN;
    observedY = NaN;
    testable = false;
end

sampleIndex = (1:numberAnimals)';
regionAvailable = reshape([animalData.regionAvailable], [], 1);
targetMoleculeCount = reshape( ...
    [animalData.targetMoleculeCount], [], 1);
targetOccupiedVoxels = reshape( ...
    [animalData.targetOccupiedVoxels], [], 1);
backgroundEligibleVoxels = reshape( ...
    [animalData.backgroundEligibleVoxels], [], 1);
invalidReason = string({animalData.invalidReason})';
animalDiagnostics = table( ...
    sampleIndex, groups, regionAvailable, targetMoleculeCount, ...
    targetOccupiedVoxels, backgroundEligibleVoxels, valid, ...
    invalidReason, ...
    'VariableNames', {'sample_index', 'group', 'region_available', ...
    'target_molecules', 'target_occupied_10um_voxels', ...
    'target_excluded_background_voxels', 'valid_for_test', ...
    'invalid_reason'});

model = struct( ...
    'testable', testable, 'animalData', animalData, ...
    'animalDiagnostics', animalDiagnostics, ...
    'valid', valid, 'groups', groups, ...
    'numberWT', numberWT, 'numberFAD', numberFAD, ...
    'xGrid', xGrid, 'yGrid', yGrid, ...
    'observedX', observedX, 'observedY', observedY);
end


function gridValues = makeCoordinateGrid(values, numberGridPoints)
values = values(isfinite(values));
if isempty(values)
    gridValues = linspace(-0.02, 1.02, numberGridPoints);
    return
end
lower = min([0; values]);
upper = max([1; values]);
padding = 0.02 .* max(upper - lower, 1);
gridValues = linspace(lower - padding, upper + padding, ...
    numberGridPoints);
end


function cdfValues = weightedSpatialCdf(positions, weights, gridValues)
totalWeight = sum(weights);
if isempty(positions) || totalWeight <= 0
    cdfValues = nan(1, numel(gridValues));
    return
end
cdfValues = arrayfun( ...
    @(coordinate) sum(weights(positions <= coordinate)), gridValues);
cdfValues = cdfValues ./ totalWeight;
end


function result = runVoxelBackgroundBootstrap( ...
        model, numberBootstrapReplicates)
result = struct( ...
    'xGrid', model.xGrid, 'yGrid', model.yGrid, ...
    'distanceX', model.observedX, 'distanceY', model.observedY, ...
    'pX', NaN, 'pY', NaN, ...
    'exceedancesX', 0, 'exceedancesY', 0, ...
    'nullMeanX', NaN, 'nullMeanY', NaN, ...
    'nullStdX', NaN, 'nullStdY', NaN, ...
    'numberBootstraps', numberBootstrapReplicates, ...
    'numberWT', model.numberWT, 'numberFAD', model.numberFAD, ...
    'animalDiagnostics', model.animalDiagnostics);
if ~model.testable
    result.numberBootstraps = 0;
    return
end

validIndices = find(model.valid);
validAnimals = model.animalData(validIndices);
validGroups = model.groups(validIndices);
numberGridPoints = numel(model.xGrid);
maximumBackgroundVoxels = max( ...
    [validAnimals.backgroundEligibleVoxels]);
batchSize = max(10, min(250, ...
    floor(2e6 ./ max(maximumBackgroundVoxels, 1))));
nullDistancesX = zeros(numberBootstrapReplicates, 1);
nullDistancesY = zeros(numberBootstrapReplicates, 1);
numberCompleted = 0;

while numberCompleted < numberBootstrapReplicates
    currentBatch = min(batchSize, ...
        numberBootstrapReplicates - numberCompleted);
    wtCdfSumX = zeros(currentBatch, numberGridPoints);
    wtCdfSumY = zeros(currentBatch, numberGridPoints);
    fadCdfSumX = zeros(currentBatch, numberGridPoints);
    fadCdfSumY = zeros(currentBatch, numberGridPoints);

    for animalIndex = 1:numel(validAnimals)
        animal = validAnimals(animalIndex);
        numberClusters = animal.targetOccupiedVoxels;
        selectedVoxels = weightedSampleWithoutReplacementRows( ...
            animal.backgroundWeights, numberClusters, currentBatch);
        if numberClusters == 1
            assignedCounts = repmat( ...
                animal.targetClusterCounts', currentBatch, 1);
        else
            [~, permutationOrder] = sort( ...
                rand(currentBatch, numberClusters), 2);
            assignedCounts = animal.targetClusterCounts( ...
                permutationOrder);
        end

        xBins = coordinateBins( ...
            animal.backgroundX, model.xGrid);
        yBins = coordinateBins( ...
            animal.backgroundY, model.yGrid);
        replicateIndex = repmat((1:currentBatch)', 1, numberClusters);
        histogramX = accumarray( ...
            [replicateIndex(:), xBins(selectedVoxels(:))], ...
            assignedCounts(:), ...
            [currentBatch, numberGridPoints]);
        histogramY = accumarray( ...
            [replicateIndex(:), yBins(selectedVoxels(:))], ...
            assignedCounts(:), ...
            [currentBatch, numberGridPoints]);
        cdfX = cumsum(histogramX, 2) ./ ...
            animal.targetMoleculeCount;
        cdfY = cumsum(histogramY, 2) ./ ...
            animal.targetMoleculeCount;
        if validGroups(animalIndex) == "WT"
            wtCdfSumX = wtCdfSumX + cdfX;
            wtCdfSumY = wtCdfSumY + cdfY;
        else
            fadCdfSumX = fadCdfSumX + cdfX;
            fadCdfSumY = fadCdfSumY + cdfY;
        end
    end

    differenceX = wtCdfSumX ./ model.numberWT - ...
        fadCdfSumX ./ model.numberFAD;
    differenceY = wtCdfSumY ./ model.numberWT - ...
        fadCdfSumY ./ model.numberFAD;
    rows = numberCompleted + (1:currentBatch);
    nullDistancesX(rows) = max(abs(differenceX), [], 2);
    nullDistancesY(rows) = max(abs(differenceY), [], 2);
    numberCompleted = numberCompleted + currentBatch;
end

result.exceedancesX = sum( ...
    nullDistancesX >= model.observedX - 1e-12);
result.exceedancesY = sum( ...
    nullDistancesY >= model.observedY - 1e-12);
result.pX = (result.exceedancesX + 1) ./ ...
    (numberBootstrapReplicates + 1);
result.pY = (result.exceedancesY + 1) ./ ...
    (numberBootstrapReplicates + 1);
result.nullMeanX = mean(nullDistancesX);
result.nullMeanY = mean(nullDistancesY);
result.nullStdX = std(nullDistancesX);
result.nullStdY = std(nullDistancesY);
end


function selected = weightedSampleWithoutReplacementRows( ...
        weights, sampleSize, numberRows)
weights = reshape(weights, 1, []);
numberCandidates = numel(weights);
if sampleSize > numberCandidates
    error('Cannot sample more background voxels than are available.');
end
if sampleSize == numberCandidates
    selected = repmat(1:numberCandidates, numberRows, 1);
    return
end
exponentialKeys = -log(max(rand(numberRows, numberCandidates), ...
    realmin('double'))) ./ weights;
[~, selected] = mink(exponentialKeys, sampleSize, 2);
end


function bins = coordinateBins(positions, gridValues)
edges = [-Inf, gridValues(1:end-1), Inf];
bins = discretize(positions, edges);
bins = reshape(bins, [], 1);
end


function result = animalLevelKsTest(targetData, fieldName, groups, gridValues)
numberAnimals = numel(targetData);
individualCdfs = nan(numberAnimals, numel(gridValues));
valid = false(numberAnimals, 1);
pooledWT = [];
pooledFAD = [];
for animalIndex = 1:numberAnimals
    values = targetData(animalIndex).(fieldName);
    values = values(isfinite(values));
    if isempty(values)
        continue
    end
    valid(animalIndex) = true;
    individualCdfs(animalIndex, :) = arrayfun( ...
        @(position) mean(values <= position), gridValues);
    if groups(animalIndex) == "WT"
        pooledWT = [pooledWT; values]; %#ok<AGROW>
    else
        pooledFAD = [pooledFAD; values]; %#ok<AGROW>
    end
end

validIndices = find(valid);
validGroups = groups(valid);
numberWT = sum(validGroups == "WT");
numberFAD = sum(validGroups == "FAD");
if numberWT < 2 || numberFAD < 2
    result = struct( ...
        'distance', NaN, ...
        'permutationP', NaN, ...
        'normalFitP', NaN, ...
        'permutedMean', NaN, ...
        'permutedStd', NaN, ...
        'numberPermutations', 0, ...
        'pooledDistance', NaN, ...
        'pooledP', NaN, ...
        'numberWT', numberWT, ...
        'numberFAD', numberFAD, ...
        'wtMolecules', numel(pooledWT), ...
        'fadMolecules', numel(pooledFAD));
    return
end

meanWT = mean(individualCdfs(valid & groups == "WT", :), 1);
meanFAD = mean(individualCdfs(valid & groups == "FAD", :), 1);
observedDistance = max(abs(meanWT - meanFAD));

combinations = nchoosek(1:numel(validIndices), numberWT);
permutedDistances = zeros(size(combinations, 1), 1);
validCdfs = individualCdfs(validIndices, :);
allIndices = 1:numel(validIndices);
for permutationIndex = 1:size(combinations, 1)
    permutedWT = combinations(permutationIndex, :);
    permutedFAD = setdiff(allIndices, permutedWT);
    difference = mean(validCdfs(permutedWT, :), 1) - ...
        mean(validCdfs(permutedFAD, :), 1);
    permutedDistances(permutationIndex) = max(abs(difference));
end
permutationP = mean(permutedDistances >= observedDistance - 1e-12);
permutedMean = mean(permutedDistances);
permutedStd = std(permutedDistances, 0);
if isfinite(permutedStd) && permutedStd > 0
    zScore = (observedDistance - permutedMean) ./ permutedStd;
    normalFitP = 0.5 .* erfc(zScore ./ sqrt(2));
    normalFitP = max(normalFitP, realmin('double'));
else
    normalFitP = double(observedDistance <= permutedMean);
end

[~, pooledP, pooledDistance] = kstest2(pooledWT, pooledFAD);
result = struct( ...
    'distance', observedDistance, ...
    'permutationP', permutationP, ...
    'normalFitP', normalFitP, ...
    'permutedMean', permutedMean, ...
    'permutedStd', permutedStd, ...
    'numberPermutations', numel(permutedDistances), ...
    'pooledDistance', pooledDistance, ...
    'pooledP', pooledP, ...
    'numberWT', numberWT, ...
    'numberFAD', numberFAD, ...
    'wtMolecules', numel(pooledWT), ...
    'fadMolecules', numel(pooledFAD));
end


function fig = plotTargetFigure( ...
        analysisName, geneName, regionName, samples, ...
        xGrid, xCurves, xValid, xBandwidth, xTest, ...
        xFdr, yGrid, yCurves, yValid, yBandwidth, yTest, yFdr)
groups = string({samples.group})';
controlColor = [0.12, 0.58, 0.24];
fadColor = [0.88, 0.20, 0.18];

fig = figure('Color', 'w', 'Position', [80, 80, 1120, 560]);
layout = tiledlayout(fig, 1, 2, ...
    'TileSpacing', 'compact', 'Padding', 'loose');
axX = nexttile(layout);
plotOneAxis(axX, xGrid, xCurves, xValid, groups, ...
    controlColor, fadColor, "Reference-map X coordinate", ...
    xBandwidth, xTest, xFdr);
axY = nexttile(layout);
plotOneAxis(axY, yGrid, yCurves, yValid, groups, ...
    controlColor, fadColor, "Reference-map Y coordinate", ...
    yBandwidth, yTest, yFdr);
legend(axY, axY.UserData.legendHandles, ...
    {'Control +/- SEM', 'Control mean', ...
    '5xFAD +/- SEM', '5xFAD mean'}, ...
    'Location', 'northeast', 'Box', 'off', 'FontSize', 9);
title(layout, { ...
    sprintf('%s spatial density in %s after whole-map reference registration', ...
    geneName, regionName), ...
    sprintf('Baseline ExSeq %s call; each animal contributes one KDE', ...
    analysisName), ...
    'Solid line = mean; shading = +/- SEM'}, ...
    'FontSize', 14, 'FontWeight', 'bold');
end


function plotOneAxis(ax, positions, curves, valid, groups, ...
        controlColor, fadColor, axisLabel, bandwidth, test, fdr)
wtRows = valid & groups == "WT";
fadRows = valid & groups == "FAD";
[wtMean, wtSem] = meanAndSem(curves(wtRows, :));
[fadMean, fadSem] = meanAndSem(curves(fadRows, :));

hold(ax, 'on');
wtPatch = fill(ax, [positions, fliplr(positions)], ...
    [max(0, wtMean - wtSem), fliplr(wtMean + wtSem)], ...
    controlColor, 'FaceAlpha', 0.20, 'EdgeColor', 'none');
wtLine = plot(ax, positions, wtMean, ...
    'Color', controlColor, 'LineWidth', 2.2);
fadPatch = fill(ax, [positions, fliplr(positions)], ...
    [max(0, fadMean - fadSem), fliplr(fadMean + fadSem)], ...
    fadColor, 'FaceAlpha', 0.20, 'EdgeColor', 'none');
fadLine = plot(ax, positions, fadMean, ...
    'Color', fadColor, 'LineWidth', 2.2);
uistack([wtLine, fadLine], 'top');
xline(ax, 0, ':', 'Color', [0.45, 0.45, 0.45]);
xline(ax, 1, ':', 'Color', [0.45, 0.45, 0.45]);

xlabel(ax, axisLabel, 'FontSize', 11);
ylabel(ax, 'Probability density', 'FontSize', 11);
title(ax, sprintf([ ...
    'KS D = %.3f; 10-um voxel-background P = %.3g; BH FDR = %.3g\n' ...
    '%d control, %d 5xFAD; reference BW = %.3f'], ...
    test.distance, test.voxelBackgroundP, fdr, ...
    test.numberWT, test.numberFAD, bandwidth), ...
    'FontSize', 8.2, 'FontWeight', 'normal');
grid(ax, 'on');
ax.GridAlpha = 0.15;
ax.Box = 'off';
ax.FontSize = 10;
xlim(ax, [min(positions), max(positions)]);
ylim(ax, [0, max([wtMean + wtSem, fadMean + fadSem]) .* 1.12]);
ax.UserData = struct( ...
    'legendHandles', [wtPatch, wtLine, fadPatch, fadLine]);
end


function [average, sem] = meanAndSem(curves)
average = mean(curves, 1, 'omitnan');
numberAnimals = sum(all(isfinite(curves), 2));
if numberAnimals <= 1
    sem = zeros(size(average));
else
    sem = std(curves, 0, 1, 'omitnan') ./ sqrt(numberAnimals);
end
end


function test = makeVoxelPlotTest(voxelTest, axisName)
if axisName == "X"
    distance = voxelTest.distanceX;
    pValue = voxelTest.pX;
else
    distance = voxelTest.distanceY;
    pValue = voxelTest.pY;
end
test = struct( ...
    'distance', distance, 'voxelBackgroundP', pValue, ...
    'numberWT', voxelTest.numberWT, ...
    'numberFAD', voxelTest.numberFAD);
end


function [xRow, yRow] = makeVoxelStatisticsRows( ...
        geneName, regionName, test, exactX, exactY, ...
        voxelSizeMicrons, minimumMolecules, minimumOccupiedVoxels)
xRow = makeOneVoxelStatisticsRow( ...
    geneName, regionName, "X", ...
    test.distanceX, test.pX, test.exceedancesX, ...
    test.nullMeanX, test.nullStdX, ...
    test, exactX, voxelSizeMicrons, minimumMolecules, ...
    minimumOccupiedVoxels);
yRow = makeOneVoxelStatisticsRow( ...
    geneName, regionName, "Y", ...
    test.distanceY, test.pY, test.exceedancesY, ...
    test.nullMeanY, test.nullStdY, ...
    test, exactY, voxelSizeMicrons, minimumMolecules, ...
    minimumOccupiedVoxels);
end


function row = makeOneVoxelStatisticsRow( ...
        geneName, regionName, axisName, distance, pValue, ...
        exceedances, nullMean, nullStd, test, exactTest, ...
        voxelSizeMicrons, minimumMolecules, minimumOccupiedVoxels)
row = table( ...
    geneName, regionName, axisName, distance, pValue, ...
    exceedances, test.numberBootstraps, nullMean, nullStd, ...
    exactTest.distance, exactTest.permutationP, ...
    exactTest.pooledDistance, exactTest.pooledP, ...
    test.numberWT, test.numberFAD, voxelSizeMicrons, ...
    minimumMolecules, minimumOccupiedVoxels, ...
    'VariableNames', {'gene', 'region', 'axis', ...
    'voxel_level_KS_D', 'voxel_background_p', ...
    'voxel_background_exceedances', 'bootstrap_replicates', ...
    'null_KS_D_mean', 'null_KS_D_std', ...
    'molecule_level_animal_KS_D', ...
    'animal_label_permutation_p', ...
    'pooled_molecule_KS_D', 'pooled_molecule_KS_p', ...
    'valid_WT_animals', 'valid_FAD_animals', ...
    'voxel_size_um', 'minimum_target_molecules', ...
    'minimum_occupied_target_voxels'});
end


function row = makeStatisticsRows( ...
        geneName, regionName, axisName, test, bandwidth, numberWT, numberFAD)
row = table( ...
    geneName, regionName, axisName, ...
    test.distance, test.permutationP, test.normalFitP, ...
    test.permutedMean, test.permutedStd, test.numberPermutations, ...
    test.pooledDistance, test.pooledP, ...
    numberWT, numberFAD, test.wtMolecules, test.fadMolecules, bandwidth, ...
    'VariableNames', {'gene', 'region', 'axis', ...
    'animal_level_KS_D', 'animal_label_permutation_p', ...
    'normal_fit_permutation_p', ...
    'permuted_KS_D_mean', 'permuted_KS_D_std', ...
    'number_label_permutations', ...
    'pooled_molecule_KS_D', 'pooled_molecule_KS_p', ...
    'valid_WT_animals', 'valid_FAD_animals', ...
    'WT_molecules', 'FAD_molecules', 'KDE_bandwidth_reference_units'});
end


function adjusted = benjaminiHochberg(pValues)
adjusted = nan(size(pValues));
valid = isfinite(pValues);
validP = pValues(valid);
numberTests = numel(validP);
if numberTests == 0
    return
end
[sortedP, order] = sort(validP);
sortedAdjusted = sortedP .* numberTests ./ transpose(1:numberTests);sortedAdjusted = flipud(cummin(flipud(sortedAdjusted)));
sortedAdjusted = min(sortedAdjusted, 1);
unsortedAdjusted = nan(numberTests, 1);
unsortedAdjusted(order) = sortedAdjusted;
adjusted(valid) = unsortedAdjusted;
end


function samples = defineExseqSamples()
% EXAMPLE sample list — replace filenames with your own CSV basenames in
% inputFolder. Required columns include gene, region_name (or region), and
% spatial coordinates (global_x_um / global_y_um / Z_um or aliases).
% Groups must be "WT" or "FAD". Keep equal counts in each group (here 6+6).
% Multiple files listed for one sample are reassembled into one animal map.
samples = makeSample("WT1", "WT", {"WT_animal1.csv"});
samples(2) = makeSample("WT2", "WT", ...
    {"WT_animal2_sectionA.csv", "WT_animal2_sectionB.csv"});
samples(3) = makeSample("WT3", "WT", {"WT_animal3.csv"});
samples(4) = makeSample("WT4", "WT", {"WT_animal4.csv"});
samples(5) = makeSample("WT5", "WT", {"WT_animal5.csv"});
samples(6) = makeSample("WT6", "WT", ...
    {"WT_animal6_sectionA.csv", "WT_animal6_sectionB.csv"});
samples(7) = makeSample("FAD1", "FAD", ...
    {"FAD_animal1_sectionA.csv", "FAD_animal1_sectionB.csv"});
samples(8) = makeSample("FAD2", "FAD", {"FAD_animal2.csv"});
samples(9) = makeSample("FAD3", "FAD", {"FAD_animal3.csv"});
samples(10) = makeSample("FAD4", "FAD", {"FAD_animal4.csv"});
samples(11) = makeSample("FAD5", "FAD", {"FAD_animal5.csv"});
samples(12) = makeSample("FAD6", "FAD", {"FAD_animal6.csv"});
end


function sample = makeSample(name, group, files)
sample = struct('name', name, 'group', group, 'files', {files});
end


function [rotationDegrees, mirrorLeftRight] = sectionOrientation( ...
        sampleName, sectionIndex) %#ok<INUSD>
% Optional per-section orientation corrections for multi-section animals.
% Defaults are no-ops. Edit for your dataset if sections need mirroring or
% rotation before whole-animal reassembly.
rotationDegrees = 0;
mirrorLeftRight = false;
end


function yAdjustment = sectionVerticalAdjustment( ...
        sampleName, sectionIndex, scale) %#ok<INUSD>
% Optional vertical offset for a section after orientation correction.
% Default is no adjustment. Edit for your dataset if needed.
yAdjustment = 0;
end


function name = findColumn(variableNames, candidates)
name = "";
normalized = lower(regexprep(variableNames, '[^a-zA-Z0-9]', ''));
for candidate = candidates
    key = lower(regexprep(candidate, '[^a-zA-Z0-9]', ''));
    index = find(normalized == key, 1);
    if ~isempty(index)
        name = variableNames(index);
        return
    end
end
end


function regionClean = standardizeRegion(regionValues)
regionRaw = strtrim(string(regionValues));
regionKey = lower(regexprep(regionRaw, '[^a-zA-Z0-9]+', '_'));
regionKey = strip(regionKey, '_');
regionClean = regionRaw;
regionClean(regionKey == "ca1") = "CA1";
regionClean(regionKey == "ca2") = "CA2";
regionClean(regionKey == "ca3") = "CA3";
regionClean(regionKey == "dg") = "DG";
regionClean(regionKey == "hilus") = "Hilus";
regionClean(regionKey == "slm") = "SLM";
regionClean(regionKey == "so") = "SO";
regionClean(regionKey == "sm") = "DG-CA1";
regionClean(regionKey == "dg_ca1") = "DG-CA1";
end


function indices = evenlySpacedIndices(numberValues, maximumValues)
if numberValues == 0
    indices = [];
elseif numberValues <= maximumValues
    indices = (1:numberValues)';
else
    indices = unique(round(linspace(1, numberValues, maximumValues)))';
end
end


function clean = sanitizeName(value)
clean = regexprep(char(value), '[^A-Za-z0-9]+', '_');
clean = regexprep(clean, '^_+|_+$', '');
end
